# Generated by Django 4.0.5 on 2022-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_imageset_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
