# Generated by Django 4.0.5 on 2022-06-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_imageset_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterField(
            model_name='imageset',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='home.works', verbose_name='Изображение работы'),
        ),
    ]
