# Generated by Django 4.0.5 on 2022-06-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_home_options_alter_imageset_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение работы'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.works', verbose_name='Изображение работы'),
        ),
    ]
