# Generated by Django 4.0.5 on 2022-06-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_works_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default='17-06-2022', verbose_name='Дата публикации'),
        ),
    ]
