# Generated by Django 4.0.5 on 2022-06-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
