# Generated by Django 4.0.5 on 2022-06-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Изображение работы'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='image', to='home.works', verbose_name='Изображение работы'),
        ),
    ]
