# Generated by Django 4.0.5 on 2022-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_imageset_options_alter_imageset_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='copywrite',
            field=models.CharField(default=1, max_length=200, verbose_name='Копирайт в подвале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='insta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='home',
            name='telega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телеграмм'),
        ),
        migrations.AddField(
            model_name='home',
            name='vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='ВК'),
        ),
    ]
