# Generated by Django 4.0.5 on 2022-06-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_home_copywrite_home_insta_home_telega_home_vk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='home',
            name='telega',
        ),
        migrations.RemoveField(
            model_name='home',
            name='vk',
        ),
    ]
