# Generated by Django 4.0.5 on 2022-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='insta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инстаграм'),
        ),
    ]
