# Generated by Django 4.0.5 on 2022-06-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_insta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ваше имя')),
                ('email', models.CharField(max_length=250, verbose_name='Удобный способ связи')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявки с формы на странице Контакты',
                'verbose_name_plural': 'Заявки с формы на странице Контакты',
            },
        ),
    ]
