# Generated by Django 4.0.5 on 2022-06-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_formcontactpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcontactpage',
            old_name='email',
            new_name='contact',
        ),
    ]
