# Generated by Django 4.0.5 on 2022-06-21 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_email_formcontactpage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontactpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
