# Generated by Django 4.0.5 on 2022-06-21 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_formcontactpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontactpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
