# Generated by Django 4.0.5 on 2022-06-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название иконки')),
                ('icon_code', models.CharField(max_length=100, verbose_name='Код иконки')),
            ],
            options={
                'verbose_name': 'Иконки услуг',
                'verbose_name_plural': 'Иконки услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок страницы')),
                ('descr', models.TextField(verbose_name='Описание страницы')),
            ],
            options={
                'verbose_name': 'Страница услуг',
                'verbose_name_plural': 'Страница услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Сортировка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок услуги')),
                ('descr', models.TextField(verbose_name='Описание Услуги')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon_small_service', to='services.servicesicon', verbose_name='Иконка услуги')),
                ('works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_service', to='services.servicesmain', verbose_name='Маленькая услуга')),
            ],
            options={
                'verbose_name': 'Маленькие услуги',
                'verbose_name_plural': 'Маленькие услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Сортировка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок услуги')),
                ('descr', models.TextField(verbose_name='Описание Услуги')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon_big_service', to='services.servicesicon', verbose_name='Иконка услуги')),
                ('works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_service', to='services.servicesmain', verbose_name='Большая услуга')),
            ],
            options={
                'verbose_name': 'Большие услуги',
                'verbose_name_plural': 'Большие услуги',
            },
        ),
    ]
