# Generated by Django 4.0.5 on 2022-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmain',
            name='title_more',
            field=models.CharField(default=1, max_length=60, verbose_name='Дополнительно'),
            preserve_default=False,
        ),
    ]
